### ISSUE TITLE
Add a way to change cache

### ISSUE THREAD

**Issue by slonoed** [fusionjs/fusion-apollo-universal-client#101]
### Type of issue

Feature request

### Description

This package hardcoded usage of InMemoryCache without any way to configure it.

**Comment by mlmorg** [comment]
Do you want to PR this?

**Comment by slonoed** [comment]
Will do.

**Comment by KevinGrandon** [comment]
Support for this was added in: https://github.com/fusionjs/fusion-apollo-universal-client/pull/134
