### ISSUE TITLE
Multiple endpoints ?

### ISSUE THREAD

**Issue by revskill10** [fusionjs/fusion-apollo-universal-client#124]
### Type of issue

Feature request

### Description

Allow multiple graphql Endpoints

### Current behavior

There's no way to register and use multiple GraphQL Endpoints.

### Expected behavior

In my case, i'd love to separate Two endpoints, the first is  for Query and Mutation, the second is for subscription

### Your environment

* fusion-apollo-universal-client version ^1.3.0:

* Node.js version 10.7.0:

* npm version 6.3.0:

* Operating System: MacOS Sierra

**Comment by KevinGrandon** [comment]
We currently recommend that you use [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html) to stitch together two remote endpoints. This would mean that you would have to host a single graphql endpoint, possibly using [fusion-plugin-apollo-server](https://github.com/fusionjs/fusion-plugin-apollo-server/).
