### ISSUE TITLE
Consider disabling cache by default when using SSR

### ISSUE THREAD

**Issue by saminzadeh** [fusionjs/fusion-apollo-universal-client#161]
Consider disabling the Apollo cache by default when using SSR

### Type of issue

Unexpected Behavior 

### Description

Recently was running into a (possibly dangerous) bug where this query (which is based on user context):

```graphql
query fetchUser {
  currentUser {
    email
  }
}
```
Was returning the credentials of a different user when using SSR. After further investigation, I _believe_ this was because the query was running server side and was caching the results of another request from a different user.

The easy solution to solve this was to change the query to use `ssr={false}` or change the fetch policy like:
```js
<Query query={CURRENT_USER_QUERY} ssr={false}>
       {...}
 </Query>
```
to avoid returning the results from the cache server side.

### Proposal: 
This can cause unexpected behavior to users who don't understand Apollo client's caching implementation. I purpose a few alternatives:

1) Turn off caching by default [everywhere:](https://github.com/fusionjs/fusion-apollo-universal-client/blob/master/src/index.js#L116)

```js
watchQuery: {
  fetchPolicy: 'no-cache', // or __NODE__ ? 'no-cache' : 'network-only'
},
query: {
  fetchPolicy: 'network-only',
},
```
2) Create a client (more specifically a cache) on every new requests for SSR. Recommended by [Apollo docs: ](https://www.apollographql.com/docs/react/features/server-side-rendering.html)

> You need to ensure that you create a new client or store instance for each request, rather than re-using the same client for multiple requests. Otherwise the UI will be getting stale data and you’ll have problems with authentication.

3) Require users to provide a Apollo caching policy token so they are explicitly aware.
```js
// Required
app.register(ApolloCachingToken, () => {
  watchQuery: {...}
   ...
})
```
### Your environment

* fusion-apollo-universal-client version: 1.4.0

* Node.js version (`node --version`): v8.11.3

* npm version (`npm --version`): yarn 1.9.4

* Operating System:
Mac

**Comment by KevinGrandon** [comment]
Thank you for the bug report. I think you're right here, it's a bit of a big footgun to cache across requests. If we can instantiate a new cache object for each request, let's do that. It feels like the safest thing to do for this "default client" that many people will use out of the box.
