### ISSUE TITLE
Allow consumer to specify defaultOptions

### ISSUE THREAD

**Issue by slonoed** [fusionjs/fusion-apollo-universal-client#180]
Value is hardcoded to `cache-and-network` for regular (nonpolling) queries.
A default value for Apollo client is `cache-first`. 

This package should repeat default behavior or give the ability to redefine defaults.

https://github.com/fusionjs/fusion-apollo-universal-client/blob/v2.0.1/src/index.js#L136

**Comment by ganemone** [comment]
We now have the `ApolloClientDefaultOptionsToken`

**Comment by ganemone** [comment]
This should be resolved with the `ApolloClientDefaultOptionsToken`
